version: '3'

services:
  database:
    image: postgres:latest
    container_name: my_database
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: Karman
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user

  adminer:
    image: adminer
    container_name: my_adminer
    ports:
      - "8080:8080"
    depends_on:
      - database
